package transcription

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/rob137/risper/internal/files"
	"github.com/rob137/risper/models"
)

// ErrNoTranscript means that the configured engine completed without printing
// or writing a transcript.
type ErrNoTranscript struct{}

func (ErrNoTranscript) Error() string { return "transcription produced no transcript" }

// TranscriptionResult records the profile that actually produced the text.
// PrimaryError is populated when the local fallback succeeded after an
// OpenAI failure; it lets the caller explain that the result is local without
// losing the cloud diagnostic.
type TranscriptionResult struct {
	Transcript   string
	Profile      models.Profile
	PrimaryError error
}

// TranscriptionFallbackError retains both failures when neither engine can
// produce a transcript. Unwrap makes errors.Is/errors.As useful for either
// underlying cause.
type TranscriptionFallbackError struct {
	Primary  error
	Fallback error
}

func (err *TranscriptionFallbackError) Error() string {
	return fmt.Sprintf("OpenAI transcription failed: %v; whisper.cpp fallback failed: %v", err.Primary, err.Fallback)
}

func (err *TranscriptionFallbackError) Unwrap() []error {
	return []error{err.Primary, err.Fallback}
}

// TranscribeWithFallback gives an OpenAI attempt a caller-supplied time
// budget, then runs the supplied whisper.cpp profile when the cloud attempt
// fails. The local profile is only started for cloud/key/HTTP/response and
// timeout failures. Input and transcript-storage failures are returned as-is
// because another engine cannot repair them.
//
// The returned Profile is always the profile that produced Transcript. When
// the fallback succeeds, PrimaryError retains the original OpenAI failure.
func TranscribeWithFallback(primary, fallback models.Profile, audioPath, rawPath, cleanPath string, cloudAttemptBudget time.Duration, onProcessStart func(pid int) error) (TranscriptionResult, error) {
	return TranscribeWithFallbackContext(context.Background(), primary, fallback, audioPath, rawPath, cleanPath, cloudAttemptBudget, onProcessStart)
}

// TranscribeWithFallbackContext is the cancellable form of
// TranscribeWithFallback. Cancellation of the parent context stops the cloud
// request and is not treated as an invitation to start local work.
func TranscribeWithFallbackContext(ctx context.Context, primary, fallback models.Profile, audioPath, rawPath, cleanPath string, cloudAttemptBudget time.Duration, onProcessStart func(pid int) error) (TranscriptionResult, error) {
	if primary.Engine != "openai" {
		return TranscriptionResult{}, fmt.Errorf("transcription fallback primary profile %q uses engine %q; want openai", primary.ID, primary.Engine)
	}
	if fallback.Engine != "whisper.cpp" {
		return TranscriptionResult{}, fmt.Errorf("transcription fallback profile %q uses engine %q; want whisper.cpp", fallback.ID, fallback.Engine)
	}
	if cloudAttemptBudget <= 0 {
		return TranscriptionResult{}, fmt.Errorf("OpenAI fallback attempt budget must be positive, got %s", cloudAttemptBudget)
	}
	if ctx == nil {
		ctx = context.Background()
	}
	// Check the input before reading the key. If the recording cannot be
	// opened, starting whisper.cpp would only produce a second misleading
	// failure and would waste the user's time.
	audio, err := os.Open(audioPath)
	if err != nil {
		return TranscriptionResult{}, &openAIInputError{err: fmt.Errorf("open audio for transcription fallback: %w", err)}
	}
	if err := audio.Close(); err != nil {
		return TranscriptionResult{}, &openAIInputError{err: fmt.Errorf("close audio for transcription fallback: %w", err)}
	}

	attemptCtx, cancel := context.WithTimeout(ctx, cloudAttemptBudget)
	transcript, primaryErr := transcribeOpenAIContext(attemptCtx, primary, audioPath, rawPath, cleanPath)
	cancel()
	if primaryErr == nil {
		return TranscriptionResult{Transcript: transcript, Profile: primary}, nil
	}
	if !fallbackEligible(primaryErr) {
		return TranscriptionResult{}, primaryErr
	}

	transcript, fallbackErr := Transcribe(fallback, audioPath, rawPath, cleanPath, onProcessStart)
	if fallbackErr != nil {
		return TranscriptionResult{}, &TranscriptionFallbackError{Primary: primaryErr, Fallback: fallbackErr}
	}
	return TranscriptionResult{Transcript: transcript, Profile: fallback, PrimaryError: primaryErr}, nil
}

func fallbackEligible(err error) bool {
	if err == nil {
		return false
	}
	var inputErr *openAIInputError
	if errors.As(err, &inputErr) {
		return false
	}
	var writeErr *transcriptWriteError
	if errors.As(err, &writeErr) {
		return false
	}
	// A caller cancellation is a lifecycle decision, not a cloud outage. A
	// timeout generated by the attempt budget remains eligible for fallback.
	return !errors.Is(err, context.Canceled)
}

// Transcribe runs the selected engine. External profiles accept either stdout
// or the raw/clean output files documented by the model profile format; the
// native OpenAI profile parses its JSON response before writing both files.
func Transcribe(profile models.Profile, audioPath, rawPath, cleanPath string, onProcessStart func(pid int) error) (string, error) {
	if profile.Engine == "openai" {
		// The native HTTP path has no child process. The controller PID remains
		// the cancellation boundary for this in-process request.
		return transcribeOpenAI(profile, audioPath, rawPath, cleanPath)
	}
	rendered := renderCommand(profile, audioPath, rawPath, cleanPath)
	cmd := exec.Command("sh", "-c", rendered)
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	if err := cmd.Start(); err != nil {
		return "", err
	}
	if onProcessStart != nil {
		if err := onProcessStart(cmd.Process.Pid); err != nil {
			_ = terminateProcessGroup(cmd.Process.Pid)
			_ = cmd.Wait()
			return "", err
		}
	}
	if err := cmd.Wait(); err != nil {
		message := strings.TrimSpace(stderr.String())
		if message != "" {
			return "", fmt.Errorf("transcription command failed: %w: %s", err, message)
		}
		return "", fmt.Errorf("transcription command failed: %w", err)
	}

	if text := strings.TrimSpace(stdout.String()); text != "" {
		if err := writeTranscript(rawPath, cleanPath, text); err != nil {
			return "", err
		}
		return text, nil
	}
	if text, ok := readTranscript(rawPath); ok {
		if err := writeText(cleanPath, text); err != nil {
			return "", err
		}
		return text, nil
	}
	if text, ok := readTranscript(cleanPath); ok {
		if err := writeText(rawPath, text); err != nil {
			return "", err
		}
		return text, nil
	}
	return "", ErrNoTranscript{}
}

// TranscribeStdin runs a whisper.cpp profile against an in-memory WAV. The
// profile's input and text output are both redirected through standard
// streams, so the caller can recognize short-lived trigger audio without
// creating a file outside a durable recording session.
func TranscribeStdin(profile models.Profile, wav []byte) (string, error) {
	return TranscribeStdinContext(context.Background(), profile, wav)
}

func TranscribeStdinContext(ctx context.Context, profile models.Profile, wav []byte) (string, error) {
	if profile.Engine != "whisper.cpp" {
		return "", fmt.Errorf("voice trigger profile %q is not a whisper.cpp profile", profile.ID)
	}
	rendered := RenderCommand(profile, "-", "-", "-")
	cmd := exec.CommandContext(ctx, "sh", "-c", rendered)
	cmd.Stdin = bytes.NewReader(wav)
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	if err := cmd.Start(); err != nil {
		return "", err
	}
	wait := make(chan error, 1)
	go func() { wait <- cmd.Wait() }()
	var runErr error
	select {
	case runErr = <-wait:
	case <-ctx.Done():
		_ = terminateProcessGroup(cmd.Process.Pid)
		<-wait
		return "", ctx.Err()
	}
	if runErr != nil {
		message := strings.TrimSpace(stderr.String())
		if message != "" {
			return "", fmt.Errorf("voice transcription command failed: %w: %s", runErr, message)
		}
		return "", fmt.Errorf("voice transcription command failed: %w", runErr)
	}
	text := strings.TrimSpace(stdout.String())
	if text == "" {
		return "", ErrNoTranscript{}
	}
	return text, nil
}

// RenderCommand expands the profile placeholders for commands that need to
// run the same backend without writing a session transcript, such as the
// benchmark command.
func RenderCommand(profile models.Profile, audioPath, rawPath, cleanPath string) string {
	replacements := map[string]string{
		"{audio}":        audioPath,
		"{raw}":          rawPath,
		"{raw_no_txt}":   strings.TrimSuffix(rawPath, filepath.Ext(rawPath)),
		"{clean}":        cleanPath,
		"{clean_no_txt}": strings.TrimSuffix(cleanPath, filepath.Ext(cleanPath)),
		"{model}":        profile.Model,
		"{language}":     profile.Language,
		"{prompt}":       profile.Prompt,
	}
	rendered := profile.Command
	for placeholder, value := range replacements {
		rendered = strings.ReplaceAll(rendered, placeholder, value)
	}
	if profile.Engine == "whisper.cpp" && !hasWhisperMaxContext(rendered) {
		// whisper.cpp's default carries all prior decoded text into later
		// segments. On a quiet mic passage that can suppress real speech; a
		// zero max-context keeps each segment acoustically grounded.
		rendered = strings.TrimSpace(rendered) + " -mc 0"
	}
	if strings.HasPrefix(rendered, "~/") && !strings.ContainsAny(rendered, " \t\n") {
		if home, err := os.UserHomeDir(); err == nil {
			rendered = filepath.Join(home, rendered[2:])
		}
	}
	return rendered
}

func hasWhisperMaxContext(command string) bool {
	for _, field := range strings.Fields(command) {
		if field == "-mc" || field == "--max-context" || strings.HasPrefix(field, "-mc=") || strings.HasPrefix(field, "--max-context=") {
			return true
		}
	}
	return false
}

func renderCommand(profile models.Profile, audioPath, rawPath, cleanPath string) string {
	return RenderCommand(profile, audioPath, rawPath, cleanPath)
}

func readTranscript(path string) (string, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	text := strings.TrimSpace(string(data))
	return text, text != ""
}

func writeTranscript(rawPath, cleanPath, text string) error {
	if err := writeText(rawPath, text); err != nil {
		return err
	}
	return writeText(cleanPath, text)
}

// WriteTranscript persists a post-processing result, such as removing the
// spoken stop word before it reaches the clipboard.
func WriteTranscript(rawPath, cleanPath, text string) error {
	return writeTranscript(rawPath, cleanPath, text)
}

func writeText(path, text string) error {
	return files.AtomicWriteText(path, strings.TrimSpace(text)+"\n")
}

// Codex gpt-5.6-sol, xhigh, prompted by Robert Kirby
